version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install aws-cdk-lib constructs
  build:
    commands:
      - echo 'Building and deploying application with Docker image'
      - export CDK_DOCKER=docker
      - cdk deploy --require-approval never --app "python3 cdk_app.py"
  post_build:
    commands:
      - echo 'Forcing ECS service update to use new container image'
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment